config/routes.rb
Fulbo::Application.routes.draw do

  root :to => "landing_page#index"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :leagues do
    resources :affiliations, only: [:create, :destroy]
    resource :fixture do
      get 'page/:page', action: :show, on: :collection
    end
  end

  resources :teams do
    resources :photos
    resources :request_inscriptions, only: [:create]
  end

  resources :sport_centers do
    resources :locations
    resources :leagues, controller: 'sport_center_leagues'
  end

  resources :profiles, only:[:index], controller: 'user_profile'

  resources :users, only:[:index]

  resources :fields do
    resources :reservations, only: [:create]
  end

  resources :fields, only:[:index]

  resources :locations do
    resources :fields
  end

  resources :matches do
    resources :goals, only: [:create, :destroy, :new]
  end

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :path => "" do
    resource :profile, only: [:show, :edit, :update], controller: 'UserProfile'
  end

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  match '/users/auth/facebook' => 'users/omniauth_callbacks#passthru'

 devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
 end

end

app/models/league.rb
class League < ActiveRecord::Base

  # == Includes
  include RRSchedule

  # == Accessors
  attr_accessible :name, :category, :number_matches, :field_price, :registration_price,
                  :requirements, :number_teams, :start_date, :point_system_attributes,
                  :affiliations_attributes, :teams_attributes, :organizer_id

  # == Validations
  validates_presence_of :name, :category, :start_date

  # == Associations
  belongs_to :organizer, class_name: 'SportCenter'
  has_one :point_system, dependent: :destroy, inverse_of: :league
  has_one :fixture, dependent: :destroy
  has_many :affiliations, dependent: :destroy
  has_many :teams, through: :affiliations
  has_many :inscription_requests,
           class_name: 'RequestInscription',
           as: :requested

  # == Callbacks
  before_create :init_point_system

  # == Nested Attributes
  accepts_nested_attributes_for :point_system, :affiliations
  accepts_nested_attributes_for :teams, allow_destroy: true

  # == FriendlyId
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  # == Instance Methods
  def affiliate(team)
    affiliations.create(team_id: team.id)
  end

  def unaffiliated(team)
    affiliations.find_by_team_id(team.id).destroy
  end

  def generate_fixture(params={})
    rules = params[:rules]
    schedule = RRSchedule::Schedule.new(teams: self.team_ids,
                                        rules: rules,
                                        start_date: self.start_date
                                       ).generate
    fixture = self.create_fixture
    nround = 1
    monday_week = get_first_monday
    week = fixture.weeks.create(number: nround,
                                start_date: monday_week,
                                end_date: monday_week + 1.week - 1.day)
    schedule.gamedays.each do |gd|
      days_diff = (monday_week.mjd - gd.date.mjd).abs
      if days_diff >= 7
        nround += 1
        monday_week += 1.week
        week = fixture.weeks.create(number: nround,
                                    start_date: monday_week,
                                    end_date: monday_week + 1.week - 1.day)
      end
      gd.games.each do |game|
        match = week.matches.create(visitor_id: game.team_a,
                                    local_id: game.team_b)
        reservation_date = DateTime.new(gd.date.year, gd.date.month, gd.date.day,
                                        game.game_time.strftime("%k").to_i,
                                        game.game_time.strftime("%M").to_i)
        match.create_reservation(field_id: game.playing_surface.to_i,
                                 reservation_date:  reservation_date)
      end
    end
  end

  private
    def init_point_system
      build_point_system if point_system.blank?
    end

    def get_first_monday
      day = self.start_date
      until day.monday? do
        day -= 1.day
      end
      day
    end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  respond_to :html, :js

  before_filter :authenticate_user!, only: [:new, :edit, :update]
  before_filter :verify_has_sport_center, only: [:new, :edit, :create, :update]
  before_filter :verify_edit_permission, only: [:edit, :update]

  def new
    @league = League.new
    @league.build_point_system
  end

  def create
    @sport_center = current_user.sport_center
    @league = @sport_center.leagues.build(params[:league])
    if @league.save
      flash[:success] = t('flash.league', message: t('flash.created'), name: @league.name)
    end
      respond_with @league
  end

  def show
    @league = League.find(params[:id])
    if request.path != league_path(@league)
      redirect_to @league, status: :moved_permanently
    end
    @point = @league.point_system
    @teams = @league.teams
    @request_inscription = RequestInscription.new()
  end

  def index
    @leagues = League.all
  end

  def edit
    @league = League.find(params[:id])
    @inscription_requests = @league.inscription_requests.where(status: :waiting)
                                                        .map(&:requester)
    @teams = @league.teams
  end

  def update
    @league = League.find(params[:id])
    if @league.update_attributes(params[:league])
      flash[:notice] = t('flash.league',
                         message: t('flash.updated'),
                         name: @league.name)
    else
      @inscription_requests = @league.inscription_requests.where(status: :waiting)
                                                          .map(&:requester)
      @teams = @league.teams
    end
    respond_with @league
  end

  def destroy
    @league = League.find(params[:id])
    @league.destroy
    flash[:notice] = t('flash.league', message: t('flash.destroyed'), name: @league.name)
    respond_with(@league)
  end

  private
    def verify_has_sport_center
      redirect_to(leagues_path, notice: t('flash.permission_league')) if current_user.sport_center.blank?
    end

    def verify_edit_permission
      @league = League.find(params[:id])
      sport_center = current_user.sport_center
      redirect_to(leagues_path, notice: t('flash.permission_league')) unless @league.organizer == sport_center
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
  CATEGORY = %w{5 6 7 8 9 10 11}

  def is_owner_of_team?
    current_user && current_user.team
  end

  def has_sent_request_to_league?(league)
    team = current_user.team
    team.inscription_requesters.exists?(requested_id: league, status: :waiting)
  end

  def playing_league?(league)
    team = current_user.team
    team.leagues.exists?(league)
  end

  def buttons_organizer_league(league)
    if current_user == league.organizer.owner
      btn_edit = content_tag(:div, class: "btn-group" ) do
        button_to t(".btn_edit"), edit_league_path(@league),
                                              method: :get,
                                              class: "edit-button"
      end
      btn_delete = content_tag(:div, class: "btn-group" ) do
        button_to t(".btn_delete"), league_path(@league),
                                                method: :delete,
                                                class: "delete-button",
                                                confirm: t(".confirm_delete_msg")
      end
      btn_edit + btn_delete
    end
  end

  def buttons_owner_team(league)
    return if league.fixture
    if is_owner_of_team? && has_sent_request_to_league?(@league)
      btn = content_tag(:div, class: "affiliation-sent-button") do
        t(".has_been_sent_affiliation")
      end
      btn and return
    end
    if is_owner_of_team? && !playing_league?(league)
      field_requested = hidden_field_tag :requested_id, league.id
      field_requested_type = hidden_field_tag :requested_type, league.class.name
      button = submit_tag t(".btn_send_affiliation"), class: "send-affiliation-button"
      form = form_for(@request_inscription,
                     url: team_request_inscriptions_path(current_user.team, league),
                     remote: true) do |f|
        field_requested + field_requested_type + button
      end
      form
    end
  end

  def fixture_league_button(league)
    if league.fixture.blank?
      link_to t(".generate_fixture"),
              new_league_fixture_path(league),
              confirm: t(".fixture_confirm"),
              class: "generate-fixture"
    else
      link_to t(".destroy_fixture"),
              league_fixture_path(league),
              method: :delete,
              confirm: t(".fixture_confirm"),
              class: "destroy-fixture"
    end
  end

  def league_fixture(league)
    if league.fixture
      link_to t("leagues.index.see_fixture"),
              league_fixture_path(league),
              class: "see-fixture"
    end
  end

  def league_status(league)
    html = ""
    if league.number_teams.present?
      if league.teams.count < league.number_teams
        html << content_tag(:div, class: "label label-success" ) do
          "#{t('leagues.index.available_inscriptions')}: #{league.number_teams - league.teams.count}"
        end
      else
        html << content_tag(:div, class: "label label-important" ) do
          t('leagues.index.unavailable_inscriptions')
        end
      end
      html << "<br>"
      html << t('leagues.index.registered')
      html << content_tag(:div, class: "label label-default" ) do
        "#{league.teams.count}/#{league.number_teams}"
      end
      html.html_safe
    else
      html << "#{t('leagues.index.registered')}"
      html << content_tag(:div, class: "label label-default" ) do
        "#{league.teams.count}/#"
      end
      html.html_safe
    end
  end

  def league_categories(league, form)
    html = ""
    LeaguesHelper::CATEGORY.each do |category|
      radio_button = form.radio_button :category, category, { }
      category_label = form.label "category_#{category}", "#{category}"
      cl = category_label + radio_button
      html << (content_tag :div, cl, class: "category").to_s
    end
    categories = content_tag :div, html.html_safe, class: "categories"
  end
end

app/views/leagues/_edit_teams_table.html.haml
%div{ id: "#{action}-table"}
  %table.teams-league
    %thead
      %th
        = I18n.t("leagues.edit.team_header_row")
      %th
        = I18n.t("leagues.edit.owner_header_row")
      %th
        = action == "affiliate" ? I18n.t("leagues.edit.action_affiliate") : I18n.t("leagues.edit.action_delete")
    - collection.each do |team|
      = render partial: "row_edit_team_table",
               locals: { team: team, action: action }

app/views/leagues/_form.html.haml
= form_for @league do |f|
  = errors_for(@league).html_safe
  %fieldset
    %legend
      = t("leagues.general_information")
    %div
      = f.label :name
      = f.text_field :name
    %div
      = f.label :start_date
      .datetime-league
        = f.text_field :start_date,
                       "data-format" => "yyyy-MM-dd",
                       class: "medium-field"
        .add-on
          %i{ "data-time-icon" => "icon-time",
              "data-date-icon" => "icon-calendar" }
    %div
      = f.label :field_price
      .field-money-league
        $
      = f.text_field :field_price, {class: "medium-field"}
    %div
      = f.label :registration_price
      .field-money-league
        $
      = f.text_field :registration_price, {class: "medium-field"}
    %div
      = f.label :number_teams
      = f.select :number_teams, (1..50).to_a,{ include_blank: true },
                 { class: "small-field" }
    %div
      = f.label :category
      = league_categories(@league, f)
    %div
      = f.label :requirements
      = f.text_area :requirements, size: "5x5"
  %fieldset
    %legend
      = t("leagues.point_system_title")
    .point-system
      = f.fields_for :point_system do |point|
        %br
        = point.label :win
        = point.select :win, (0..20).to_a, class: "small-field"
        %br
        = point.label :tie
        = point.select :tie, (0..20).to_a, class: "small-field"
        %br
        = point.label :loose
        = point.select :loose, (0..20).to_a, class: "small-field"
  = f.submit t('leagues.btn_submit'), class: 'button-form'

app/views/leagues/_league.html.haml
.container-league
  .badge-tournament
    %a{ href: league_path(league) }
      = image_tag "league_default.png", size: "64x64"
  .tournament-information
    .name-category
      = link_to "#{t('leagues.index.name')}: #{league.name}", league_path(league)
      %br
      ="#{t('leagues.index.category')}: #{league.category}"
    .status
      = league_status(league)
    .organizer-date
      = t('leagues.index.organizer')
      = link_to league.organizer.name, sport_center_path(league.organizer)
      %br
      = t('leagues.index.start_date')
      .label.label-info
        = league.start_date
    .fixture
      = league_fixture(league)

app/views/leagues/_row_edit_team_table.html.haml
%tr
  %td
    .text-left
      = link_to team.name, team_path(team)
  %td
    .text-left
      = link_to "#{team.owner.name} #{team.owner.profile.surname}", user_profile_path(team.owner)
  %td
    .text-left
      - if action == "remove"
        .unaffiliation
          = form_for([@league, @league.affiliations.find_by_team_id(team)], method: :delete, remote: :true)  do |f|
            = f.submit I18n.t('leagues.edit.action_delete'), class: "btn btn-small btn-danger"
      - else
        .affiliation
          = form_for([@league, @league.affiliations.build(team_id: team.id)], html: {id: "new_affiliation_#{team.id}"},  remote: :true) do |f|
            = f.hidden_field :team_id
            = f.submit I18n.t('leagues.edit.action_affiliate'), class: "btn btn-small btn-primary"

app/views/leagues/affiliation.js.erb
$('.affiliation').bind('ajax:success', function() {
    $(this).closest('tr').fadeOut();
});

app/views/leagues/edit.html.haml
.container-league
  .navigation-league-edit
    %ul.nav.nav-tabs
      %li.active
        = link_to t(".information"), "#information-league", "data-toggle" => "tab"
      %li
        = link_to t(".teams"), "#teams-league", "data-toggle" => "tab"

    .tab-content
      #information-league.tab-pane.active
        .title-league
          = t(".title")
        .form-league
          = render 'form'

      #teams-league.tab-pane
        .title-league
          = t(".title")
        .list-teams
          .title-league
            = t(".my_teams_table")
          = render partial: "edit_teams_table",
                   locals: { collection: @teams, action: "remove" }
        = fixture_league_button(@league)
        .list-teams
          .title-league
            = t(".teams_table")
          = render partial: "edit_teams_table",
                   locals: { collection: @inscription_requests,
                             action: "affiliate" }

app/views/leagues/index.html.haml
.container-league
  .title-league
    = t(".title")
  %table.tournaments
    - @leagues.each do |league|
      %tr
        %td
          = render 'league', league: league

app/views/leagues/new.html.haml
.container-league
  .title-league
    = t (".title")
  .form-league
    = render "form"

app/views/leagues/show.html.haml
.container-league
  .title-league
    = t(".title")
    =": #{@league.name}"
  .information
    .general
      .text-center
        %h3= t(".data")
      %ul
        %li
          %strong= "#{t(".organizer")}:"
          = link_to @league.organizer.name, "#"
        %br
        %li
          %strong= "#{t(".category")}:"
          = @league.category
        %br
        %li
          %strong= "#{t(".start_date")}:"
          = @league.start_date
        %br
        %li
          %strong= "#{t(".number_teams")}:"
          = @league.number_teams
        %br
        %li
          %strong= "#{t(".registration_price")}: $"
          = @league.registration_price
        %br
        %li
          %strong= "#{t(".field_price")}: $"
          = @league.field_price
        %br
        %li
          %strong= "#{t(".requirements")}:"
          = @league.requirements
        %br
    .point-system
      .text-center
        %h3= t(".point_system_title")
      %ul
        %br
        %li
          %strong= "#{t(".win")}:"
          = @point.win
        %br
        %li
          %strong= "#{t(".tie")}:"
          = @point.tie
        %br
        %li
          %strong= "#{t(".loose")}:"
          = @point.loose
  .buttons-league
    = buttons_organizer_league(@league)
    = buttons_owner_team(@league)
    %br
    = league_fixture(@league)
  .league-players
    .title-players
      = t(".teams_of_league")
    %table.players
      %thead
        %th
          = t(".team_header_row")
        %th
          = t(".owner_header_row")
      - @teams.each do |team|
        %tr
          %td
            = link_to team.name, team_path(team)
          %td
            = link_to "#{team.owner.name} #{team.owner.profile.surname}",
                      user_profile_path(team.owner)

app/views/leagues/unaffiliation.js.erb
$('.unaffiliation').bind('ajax:success', function() {
    $(this).closest('tr').fadeOut();
    var newRow = "<%= j render 'row_edit_team_table', team: @team, action: I18n.t('leagues.edit.action_affiliate') %>"
    var nameTable = "#<%= j I18n.t('leagues.edit.action_affiliate') %>_table .table"
    $(nameTable).append(newRow);
});