config/routes.rb
Fulbo::Application.routes.draw do

  root :to => "landing_page#index"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :leagues do
    resources :affiliations, only: [:create, :destroy]
    resource :fixture do
      get 'page/:page', action: :show, on: :collection
    end
  end

  resources :teams do
    resources :photos
    resources :request_inscriptions, only: [:create]
  end

  resources :sport_centers do
    resources :locations
    resources :leagues, controller: 'sport_center_leagues'
  end

  resources :profiles, only:[:index], controller: 'user_profile'

  resources :users, only:[:index]

  resources :fields do
    resources :reservations, only: [:create]
  end

  resources :fields, only:[:index]

  resources :locations do
    resources :fields
  end

  resources :matches do
    resources :goals, only: [:create, :destroy, :new]
  end

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :path => "" do
    resource :profile, only: [:show, :edit, :update], controller: 'UserProfile'
  end

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  match '/users/auth/facebook' => 'users/omniauth_callbacks#passthru'

 devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
 end

end

app/models/fixture.rb
class Fixture < ActiveRecord::Base

  # == Associations
  belongs_to :league
  has_many :weeks, dependent: :destroy
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  respond_to :js, :html
  before_filter :authenticate_user!, only: [:new, :create, :edit, :destroy]
  before_filter :check_new_permission, only: [:new, :create]
  before_filter :check_exist_fixture, only: [:show, :edit, :destroy]
  before_filter :check_edit_permission, only: [:edit, :destroy]

  def show
    @weeks = @league.fixture.weeks.order(:number).page(params[:page]).per(1)
    @week = @weeks.first
  end

  def new
    @days = params[:days]
    respond_to do |format|
      format.html do
        if request.xhr?
          render partial: 'fixtures/time_and_place', days: @days
        end
      end
    end
  end

  def create
    @rules = params[:rules].map { |rule|
      # wday - week day.
      # gt - game times.
      # ps - playing surfaces.
      RRSchedule::Rule.new(wday: rule[:day].to_i,
                           gt: dispatch_time(time_from: rule[:time_from],
                                             time_to: rule[:time_to]),
                           ps: rule[:fields])
    }
    @league.generate_fixture(rules: @rules)
    flash[:success] = t('flash.fixture',
                         message: t('flash.created'),
                         name: @league.name)
    redirect_to league_fixture_path(@league)
  end

  def edit
    @weeks = @league.fixture.weeks.order(:number).page(params[:page]).per(1)
    @week = @weeks.first
    @fields = @league.organizer.fields
    @match = Match.new(week_id: @week.id)
  end

  def destroy
    if @league.fixture.destroy
      flash[:notice] = t('flash.fixture',
                         message: t('flash.destroyed'),
                         name: @league.name)
    end
    respond_with @league
  end

  private
    def check_exist_fixture
      @league = League.find(params[:league_id])
      redirect_to league_path(@league) if @league.fixture.blank?
    end

    def check_new_permission
      @league = League.find(params[:league_id])
      owner = @league.organizer.owner
      redirect_to league_path(@league) and return unless owner == current_user
      redirect_to league_path(@league) and return if @league.fixture
    end

    def check_edit_permission
      owner = @league.organizer.owner
      redirect_to league_path(@league) unless owner == current_user
    end

    def dispatch_time(params={})
      t_from = params[:time_from]
      t_to = params[:time_to]
      t_game = params[:time_game] || 1.hour
      t_h = t_from.scan(/\d{2}/).first
      t_m = t_from.scan(/\d{2}/).last
      t_from = Time.new(2013,1,01, t_h,t_m,0, "+00:00")
      t_h = t_to.scan(/\d{2}/).first
      t_m = t_to.scan(/\d{2}/).last
      t_to = Time.new(2013,1,01, t_h,t_m,0, "+00:00")
      game_times = []
      t_iterator = t_from
      while t_iterator < t_to
        game_times << t_iterator.strftime( "%k:%M %p")
        t_iterator += t_game
      end
      game_times
    end
end

app/helpers/fixtures_helper.rb
module FixturesHelper

  def fixture_days
    options = ""
    t("date.day_names").each_with_index do |day, index|
      check_box = check_box_tag index, day
      day_label = label_tag "day_label", day
      options << check_box + day_label
    end
    options_div = content_tag :div, options.html_safe, class: "check_days"
  end

  def fixture_places(league)
    options = ""
    league.organizer.fields.each do |field|
      check_box = check_box_tag "rules[][#{:fields}][]", field.id
      label = label_tag "place_label", field.name
      options << check_box + label
    end
    options.html_safe
  end

  def edit_fixture_button(league)
    if league.organizer.owner == current_user
      link_to t(".edit_fixture"),
              edit_league_fixture_path(league),
              class: "edit-button"
    end
  end
end

app/views/fixtures/_edit_matches.html.haml
- week.matches.each do |match|
  %li{ id: "match_#{match.id}" }
    .match-fixture-edit
      .local-team
        = link_to match.local.name, team_path(match.local)
      .vs-match
        vs
      .visitor-team
        = link_to match.visitor.name, team_path(match.visitor)
      .match-date
        = match.reservation.reservation_date.strftime("%d/%m/%Y - %H:%M")
      .match-place
        = link_to match.reservation.field.name,
                    location_field_path(match.reservation.field.location ,
                                        match.reservation.field)
      .buttons-match-edit
        = link_to "#", id: "openmodal-match",
                  "data-match" => "#{match.id}",
                  "title" => I18n.t("fixtures.edit.tooltip_edit") do
          %i.icon-pencil
        = link_to match_path(match), method: :delete,
                  "title" => I18n.t("fixtures.edit.tooltip_delete"),
                  confirm: I18n.t("fixtures.edit.confirm_delete"),
                  class: "delete-match",
                  remote: true do
          %i.icon-remove
        = link_to edit_match_path(match),
                  class: "add-result",
                  "title" => I18n.t("fixtures.edit.tooltip_result") do
          %i.icon-edit

  %div.hide{ id: "modal-edit-match-info-#{match.id}" }
    = form_for match, remote: true, format: :json do |f|
      .form_edit
        .header
          .close{"data-dismiss" => "modal"} x
          .title-edit-fixture
            = I18n.t("fixtures.edit.title_match")
        .body
          .edit-fixture-teams
            = I18n.t("fixtures.edit.local_team")
          = f.collection_select :local_id, @league.teams, :id, :name_with_owner
          .edit-fixture-teams
            = I18n.t("fixtures.edit.visitor_team")
          = f.collection_select :visitor_id, @league.teams, :id, :name_with_owner
          = f.fields_for :reservation_attributes, match.reservation  do |r|
            .edit-fixture-fields
              = I18n.t("fixtures.edit.field")
            = r.collection_select :field_id, @fields, :id, :name
            .edit-fixture-fields
              = I18n.t("fixtures.edit.reservation_datetime")
            .modal-new-match-datetime
              = r.text_field :reservation_date,
                             "data-format" => "dd/MM/yyyy hh:mm"
              .add-on
                %i{ "data-time-icon" => "icon-time",
                    "data-date-icon" => "icon-calendar" }
        .footer
          = f.submit I18n.t("fixtures.edit.save_changes"),
                     class: "btn-edit-match"

app/views/fixtures/_matches.html.haml
- week.matches.each do |match|
  %li
    .match-fixture
      .local-team
        = profile_badge(match.local.profile, :thumbnail_badge)
        = link_to match.local.name, team_path(match.local)
      .vs-match
        vs
      .vistior-team
        = link_to match.visitor.name, team_path(match.visitor)
        = profile_badge(match.visitor.profile, :thumbnail_badge)
      .match-date
        = match.reservation.reservation_date.strftime("%e-%b %I:%M %p")
      .match-place
        = link_to match.reservation.field.name,
                    location_field_path(match.reservation.field.location ,
                                        match.reservation.field)

app/views/fixtures/_new_match_fixture.html.haml
#modal-add-match
  = form_for match, remote: true, format: :json do |f|
    .form_edit
      .header
        .close{"data-dismiss" => "modal"} x
        .title-edit-fixture
          = I18n.t("fixtures.edit.add_match")
      .body
        .edit-fixture-teams
          = I18n.t("fixtures.edit.local_team")
        = f.collection_select :local_id, @league.teams, :id, :name_with_owner
        .edit-fixture-teams
          = I18n.t("fixtures.edit.visitor_team")
        = f.collection_select :visitor_id, @league.teams, :id, :name_with_owner
        = f.hidden_field :week_id
        = f.fields_for :reservation_attributes do |r|
          .edit-fixture-fields
            = I18n.t("fixtures.edit.field")
          = r.collection_select :field_id, @fields, :id, :name
          .edit-fixture-fields
            = I18n.t("fixtures.edit.reservation_datetime")
          .modal-new-match-datetime
            = r.text_field :reservation_date,
                           "data-format" => "dd/MM/yyyy hh:mm"
            .add-on
              %i{ "data-time-icon" => "icon-time",
                  "data-date-icon" => "icon-calendar" }
      .footer
        = f.submit I18n.t("fixtures.edit.save_changes"),
                   class: "btn-edit-match"

app/views/fixtures/_time_and_place.html.haml
= form_tag league_fixture_path do
  - @days.each do |day|
    .time-and-place{ "data-field" => 0 }
      = hidden_field_tag "rules[][day]", day
      .title-time-and-place
        = "#{I18n.t('fixtures.new.title')}: #{I18n.t("date.day_names")[day.to_i]}"
      .fixture-label-text
        = "#{I18n.t("fixtures.new.text_time")}:"
      .fixture-time
        = label_tag I18n.t("fixtures.new.start"), nil, class: "time-label"
        .pick_time_fixture
          = text_field_tag "rules[][#{:time_from}]","15:00", class: "time-field",
                           "data-format" => "hh:mm"
          .add-on
            %i{ "data-time-icon" => "icon-time",
                "data-date-icon" => "icon-calendar" }
        = label_tag I18n.t("fixtures.new.finish"), nil, class: "time-label"
        .pick_time_fixture
          = text_field_tag "rules[][#{:time_to}]", "16:00", class: "time-field",
                           "data-format" => "hh:mm"
          .add-on
            %i{ "data-time-icon" => "icon-time",
                "data-date-icon" => "icon-calendar" }
      .fixture-label-text
        = "#{I18n.t("fixtures.new.text_place")}:"
      .fixture-place
        = fixture_places(@league)
  = submit_tag I18n.t("fixtures.new.create_fixture"),
               confirm: I18n.t("fixtures.new.confirm_create"),
               class: "btn-create-fixture"

app/views/fixtures/edit.html.haml
.container-fixture
  .title-edit-fixture
    = t (".title")
  = paginate @weeks, remote: true
  .week-information-edit
    = "#{t('fixtures.show.week_number')}-#{@week.number}"
    = "#{t('fixtures.show.week_start')}-#{@week.start_date.strftime("%d/%m/%Y")} #{t('fixtures.show.week_end')}-#{@week.end_date.strftime("%d/%m/%Y")}"
  .add-match
    = link_to "#", id: "add-match", "title" => t(".tooltip_add") do
      %i.icon-plus

  %ul#matches-of-week-edit
    %li.header
      .hlocal
        = t("fixtures.show.local")
      .hvs
        vs
      .hvisitor
        = t("fixtures.show.visitor")
      .hdate
        = t("fixtures.show.date_time")
      .hplace
        = t("fixtures.show.place")
      .hactions
        = t(".actions")
    = render "edit_matches", week: @week

.new-match
  = render "new_match_fixture", match: @match

app/views/fixtures/edit.js.haml
$("#modal-add-match").remove();
$(".new-match").html('#{ j (render "new_match_fixture", match: @match)}');
var matches = '#{ j (render "edit_matches", week: @week)}';
$('#matches-of-week-edit li:not(:first)').remove();
$('#matches-of-week-edit li:first').after(matches);
$('.pagination').html('#{ j (paginate(@weeks, remote: true).to_s) }');
var wnumber =  "#{t('fixtures.show.week_number')}-#{@week.number} ";
var wstart = "#{t('fixtures.show.week_start')}-#{@week.start_date.strftime("%d/%m/%Y")} ";
var wend = "#{t('fixtures.show.week_end')}-#{@week.end_date.strftime("%d/%m/%Y")}";
$('.week-information-edit').html(wnumber + wstart + wend);

app/views/fixtures/new.html.haml
.container-fixture
  .fixture-days
    .title-new-fixture
      = t(".title_days")
    = fixture_days
  .fixture-time-and-place
    .title-new-fixture
      = t(".title_times_and_places")
  .creation-nav
    %ul
      %li
        = link_to t(".back_step"),
                  new_league_fixture_path(@league),
                  id: "back_step"
      %li
        = link_to t(".next_step"),
                  new_league_fixture_path(@league),
                  id: "next_step"

app/views/fixtures/show.html.haml
.container-fixture
  .title-show-fixture
    = t (".title")
  = paginate @weeks, remote: true
  .week-information
    = "#{t('.week_number')}-#{@week.number}"
    = "#{t('.week_start')}-#{@week.start_date} #{t('.week_end')}-#{@week.end_date}"
  .edit-fixture
    = edit_fixture_button @league
  %ul#matches-of-week
    %li.header
      .hlocal
        = t(".local")
      .hvs
        vs
      .hvisitor
        = t(".visitor")
      .hdate
        = t(".date_time")
      .hplace
        = t(".place")
    = render "matches", week: @week

app/views/fixtures/show.js.haml
var matches = '#{ j (render "matches", week: @week)}';
$('#matches-of-week li:not(:first)').remove();
$('#matches-of-week li:first').after(matches);
$('.pagination').html('#{ j (paginate(@weeks, remote: true).to_s) }');
var wnumber =  "#{t('.week_number')}-#{@week.number} ";
var wstart =  "#{t('.week_start')}-#{@week.start_date} ";
var wend = "#{t('.week_end')}-#{@week.end_date}";
$('.week-information').html(wnumber + wstart + wend);