config/routes.rb
Fulbo::Application.routes.draw do

  root :to => "landing_page#index"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :leagues do
    resources :affiliations, only: [:create, :destroy]
    resource :fixture do
      get 'page/:page', action: :show, on: :collection
    end
  end

  resources :teams do
    resources :photos
    resources :request_inscriptions, only: [:create]
  end

  resources :sport_centers do
    resources :locations
    resources :leagues, controller: 'sport_center_leagues'
  end

  resources :profiles, only:[:index], controller: 'user_profile'

  resources :users, only:[:index]

  resources :fields do
    resources :reservations, only: [:create]
  end

  resources :fields, only:[:index]

  resources :locations do
    resources :fields
  end

  resources :matches do
    resources :goals, only: [:create, :destroy, :new]
  end

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :path => "" do
    resource :profile, only: [:show, :edit, :update], controller: 'UserProfile'
  end

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  match '/users/auth/facebook' => 'users/omniauth_callbacks#passthru'

 devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
 end

end

app/models/sport_center.rb
class SportCenter < ActiveRecord::Base

  # == FriendlyId
  extend FriendlyId
  friendly_id :slug, use: [:slugged, :history]

  # == Validations
  validates_presence_of :address, :cuit, :description, :email, :name, :phone
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/
  validates :name, length: {maximum: 40}
  validates :description, length: {maximum: 100}
  validates :phone, length: {maximum: 20}

  # == Associations
  belongs_to :owner, :class_name => 'User', :validate => true
  has_many :leagues, foreign_key: "organizer_id", dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :fields, :through => :locations

  # == Accessors
  attr_accessible :address, :cuit, :description,
                  :email, :name, :phone, :owner_id, :slug

  # == Instance Methods
  def reservations
    locations.map(&:reservations).flatten
  end
end

app/controllers/sport_centers_controller.rb
  class SportCentersController < ApplicationController
  respond_to :html

  before_filter :authenticate_user!, :check_ownership, except: [:show, :index]

  def index
    @sport_centers = SportCenter.all
  end

  def index
    @sport_center = SportCenter.all
  end

  def edit
  end

  def update
    if @sport_center.update_attributes(params[:sport_center])
      flash[:notice] = t('flash.sport_center', message: t('flash.updated'))
    end
    respond_with @sport_center
  end

  def show
    @sport_center = SportCenter.find(params[:id])
  end

  private

  def check_ownership
    other_sport_center = SportCenter.find(params[:id])
    @sport_center = current_user.sport_center

    unless other_sport_center && @sport_center.id == other_sport_center.id
      redirect_to sport_centers_path,
                  notice: t('.flash.permission_sport_center')
    end
  end
end

app/helpers/sport_centers_helper.rb
module SportCentersHelper

  def reservation_calendar(resource)
    if has_permission?(resource)
      link_to I18n.t('sport_centers.show.reservation_calendar'),
              calendar_url(resource)
    end
  end

  private
  def has_permission?(resource)
    case resource.class.to_s
    when 'SportCenter'
      current_user == resource.owner
    when 'Field'
      current_user == resource.location.sport_center.owner
    when 'Location'
      current_user == resource.sport_center.owner
    else
      false
    end
  end

  def calendar_url(resource)
    resource_kind = resource.class.to_s.tableize
    url_for :controller => 'calendars',
            :action => 'show',
            (resource_kind.singularize + '_id').to_sym => resource.id
  end
end

app/views/sport_centers/_data.html.haml
= f.label :address
= f.text_field :address
= f.label :cuit
= f.text_field :cuit
= f.label :phone
= f.text_field :phone
= f.label :email
= f.text_field :email
= f.label :description
= f.text_field :description

app/views/sport_centers/edit.html.haml
%h2= t(".title")
= form_for @sport_center, url: sport_center_path(@sport_center) do |f|
  = errors_for(@sport_center).html_safe
  = render  "data", :f => f
  %div
    = f.submit t(".btn_submit"),:class => "btn"

app/views/sport_centers/index.html.haml
.container
  .container-layout
    %legend.title
      = t('.title')

    .sport-centers
      %ul.thumbnails
        - @sport_centers.each do |sc|
          %li.sport-center
            %img.pull-left.span2.clearfix{:alt => "Team_Picture", :src => image_path("sport_center.jpg"), :style => "margin-right:10px", :size => "64x64"}/
            .pull-left
              .name
                %h4
                  %a{:class => "media-heading"}
                    = link_to "#{sc.name}", sc
              .address
                = "#{t('.address')}:"
                = sc.address
              .phone
                = "#{t('.phone')}:"
                = sc.phone

              %ul.fields
                .title_fields
                  %h4
                    = t('.title_fields')
                - sc.fields.each do |field|
                  %h4
                  %a{:class => "media-heading"}
                    = link_to "#{field.name}", location_field_path(field.location_id, field)

app/views/sport_centers/show.html.haml
%h1 #{@sport_center.name}
.container-fluid
  .row-fluid
    .span2
      #top_navigation= render_navigation :expand_all => true, :renderer => :bootstrap
      = reservation_calendar(@sport_center)

    .span6
      %div{:class => "well well-large"}
        %div{:class => "dl-horizontal"}
          %dt= "#{t(".address")}:"
          %dd= @sport_center.address
          %dt= "#{t(".cuit")}:"
          %dd= @sport_center.cuit
          %dt= "#{t(".phone")}:"
          %dd= @sport_center.phone
          %dt= "#{t(".email")}:"
          %dd= @sport_center.email
          %dt= "#{t(".description")}:"
          %dd= @sport_center.description
        %a.btn.btn-primary{:href => edit_sport_center_path(@sport_center)}
          = t(".change")
    .span4
      .img-polaroid
        %h3= t(".logo")
        = link_to image_tag('complejo.jpg'), '#'
        %a.btn.btn-primary{:href => edit_sport_center_path(@sport_center)}
          = t(".change")