config/routes.rb
Fulbo::Application.routes.draw do

  root :to => "landing_page#index"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :leagues do
    resources :affiliations, only: [:create, :destroy]
    resource :fixture do
      get 'page/:page', action: :show, on: :collection
    end
  end

  resources :teams do
    resources :photos
    resources :request_inscriptions, only: [:create]
  end

  resources :sport_centers do
    resources :locations
    resources :leagues, controller: 'sport_center_leagues'
  end

  resources :profiles, only:[:index], controller: 'user_profile'

  resources :users, only:[:index]

  resources :fields do
    resources :reservations, only: [:create]
  end

  resources :fields, only:[:index]

  resources :locations do
    resources :fields
  end

  resources :matches do
    resources :goals, only: [:create, :destroy, :new]
  end

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :path => "" do
    resource :profile, only: [:show, :edit, :update], controller: 'UserProfile'
  end

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  match '/users/auth/facebook' => 'users/omniauth_callbacks#passthru'

 devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
 end

end

app/models/field.rb
# == Schema Information
#
# Table name: fields
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  type        :string(255)
#  category    :string(255)
#  price       :decimal(8, 2)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Field < ActiveRecord::Base
  serialize :description, Array

  # == Accessors
  attr_accessible :category, :description, :name, :price, :surface

  # == Validations
  validates_presence_of :name,:category,:surface

   # == Associations
  belongs_to :location
  has_many :reservations

  # == Delegators
  delegate :owner, to: :location

  # == Instance Methods
  def complete_name
  	name + " (#{location.sport_center.name} , #{location.name})"
  end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  respond_to :html

  before_filter :verify_permission, only: [:edit,:new]

  def edit
    @field = Field.find(params[:id])
    @sport_center = @field.location.sport_center
  end

  def new
    @field = Field.new
    @location = Location.find(params[:location_id])
    @sport_center = @location.sport_center
  end

  def create
    @location = Location.find(params[:location_id])
    @field = @location.fields.build(params[:field])
    if @field.save
      flash[:success] = t('flash.field', message: t('flash.created'))
    end
    respond_with(@field.location, @field)
  end

  def show
    @field = Field.find(params[:id])
    @location = @field.location
    @sport_center = @location.sport_center
  end

  def update 
    @field = Field.find(params[:id])
    if @field.update_attributes(params[:field])
      flash[:success] = t('flash.field', message: t('flash.updated'))
    end
    respond_with(@field.location, @field, location: location_field_path)
  end

  def destroy
    @field = Field.find(params[:id])
    @field.destroy
    flash[:success] = t('flash.field', message: t('flash.destroyed'))
    respond_with(@field.location.sport_center, @field.location)
  end

  def index
    @sport_center =  current_user.sport_center
  end

  private

      def verify_permission
        @location = Location.find(params[:location_id])
        redirect_to(sport_center_path(current_user.sport_center), notice: t('.flash.permission_field')) unless current_user.sport_center == @location.sport_center
      end

end

app/helpers/fields_helper.rb
module FieldsHelper

  CATEGORY = %w{5 6 7 8 9 10 11}
  SURFACE = %w{sand grass parquet synthetic_grass land cement}
  DESCRIPTION = %w{roofed illuminated}

  def rent_button(form)
    if user_signed_in?
      form.submit t('.btn_rent'), class: 'btn btn-primary'
    else
      link_to t('.btn_login'),
        new_user_session_path,
        class: 'btn btn-primary'
    end
  end

end

app/views/fields/_data.html.haml
= f.label :name
= f.text_field :name
%br
= f.label :surface
= f.select :surface, FieldsHelper::SURFACE.map { |s| [t("fields.surfaces.#{s}"), s] }, {:include_blank => true}
%br
= f.label :category
= f.select :category, FieldsHelper::CATEGORY, {:include_blank => true}
%br
= f.label :price
= f.text_field :price
%br
= f.label :description  
%div{:class => "form-inline"}
  - FieldsHelper::DESCRIPTION.each do |description|
    = f.check_box :description, {:multiple => true}, description, nil
    = f.label t("fields.descriptions.#{description}")
    

app/views/fields/edit.html.haml
%br
%h1= t '.title'
.container-fluid
  .row-fluid
    .span2
      #top_navigation= render_navigation :expand_all => true, :renderer => :bootstrap 
    .span8
      %div{:class => "well well-large"}
        %div{:class => "dl-horizontal"}
          = form_for @field, url: location_field_path(@field.location, @field) do |f|
            = errors_for(@field).html_safe
            = render "data", :f => f
            %div
            = f.submit t('.btn_submit'),:class => "btn pull-right"

app/views/fields/index.html.haml
%br
%h1= t(".title", :sport_center_name => @sport_center.name)

.container-fluid
  .row-fluid
    .span2
      #top_navigation
        = render_navigation :expand_all => true, :renderer => :bootstrap
      %br
    .span6
      %div{:class => "well well-large"}
        %div{:class => "dl-horizontal"}
          %table{:class => "table table-striped"}
            - @sport_center.fields.each do |field|
              %tr
                %td
                  %div{:class => "media"}
                    %a{:class => "pull-left", :href => "#"}
                    %div{:class => "media-body"}
                      %h4{:class => "media-heading"}
                        =link_to "#{field.name}",
                                 location_field_path(field.location, field)
                      %h6{:class => "media-heading"}
                        =link_to "#{t('.location')}: #{field.location.name}",
                                 sport_center_location_path(@sport_center, field.location)
                %td
                  %div{:class => "btn-group"}
                    = button_to t('.btn_edit'),
                                edit_location_field_path(field.location, field),
                                { method: :get,
                                  class: "btn btn-mini btn-info",
                                  type: "button" }

app/views/fields/new.html.haml
%br
%h1= t('.title')
.container-fluid
  .row-fluid
    .span2
      #top_navigation= render_navigation :expand_all => true, :renderer => :bootstrap
    .span8
      %div{:class => "well well-large"}
        %div{:class => "dl-horizontal"}
          = form_for @field, url: location_fields_path(@location, @field) do |f|
            = errors_for(@field).html_safe
            = render  "data", :f => f
            %br
            %div
            = f.submit t('.btn_submit'),:class => "btn pull-right"

app/views/fields/show.html.haml
.field
  .container
    .span11.offset
      %legend
        =  "#{t '.title'} #{@location.sport_center.name}"

      .container-fluid
        .row-fluid
          .span2
            #top_navigation= render_navigation :expand_all => true, :renderer => :bootstrap
          .span6
            %div{:class => "well well-large"}
              %div{:class => "dl-horizontal"}
                %dt= "#{Field.human_attribute_name(:name)}: "
                %dd= @field.name
                %br
                %dt= "#{Field.human_attribute_name(:surface)}: "
                %dd= t("fields.surfaces.#{@field.surface}")
                %br
                %dt= "#{Field.human_attribute_name(:category)}: "
                %dd= @field.category
                %br
                %dt= "#{Field.human_attribute_name(:price)}: "
                %dd= "$ #{@field.price}"
                %br
                %dt= "#{Field.human_attribute_name(:description)}: "
                %dd= (@field.description.map { |d| t("fields.descriptions.#{d}")}).to_sentence
                %br
                %dt= "#{t('.location')}: "
                %dd= link_to "#{@location.name}", sport_center_location_path(@location.sport_center, @location)
              %br
            
            = form_for [@field, Reservation.new] do |f|
              %a.btn.btn-primary{:href => edit_location_field_path(@field.location_id, @field)}
                = t('.btn_edit')

              #datetimepicker2.input-append
                = f.text_field :reservation_date, :data_format => "MM/dd/yyyy HH:mm PP", :type => "text"
                %span.add-on
                  %i{"data-date-icon" => "icon-calendar", "data-time-icon" => "icon-time"}

              = rent_button(f)